### ISSUE TITLE
Add docker image 

### ISSUE THREAD

**Issue by VovaStelmashchuk** [Das-Felix/ownshare#2]
Please add a docker image to easy deploy for every one, also a sample with docker compose will good

**Comment by Das-Felix** [comment]
Hello, i have provided the Dockerfile and a docker-compose.yml file to run OwnShare with docker. Thanks for the suggestion.

**Comment by zarevskaya** [comment]
I am not more successful.

created admin user

Warning: file_put_contents(/var/www/html/api/config.php): Failed to open stream: Permission denied in /var/www/html/api/installer.php on line 56
updated config set APP_SETUP_COMPLETE to true, this endpoint is now unavailable!
You can now login to the dashboard with username: admin, password: admin.
It is recommended to then create a new admin user and delete the default one for security reasons!
