### ISSUE TITLE
error during build

### ISSUE THREAD

**Issue by zarevskaya** [Das-Felix/ownshare#5]
Hi,

I find your project interesting but I'm having difficulty installing it.

OS: Debian 12 full updated
Docker + docker-compose V2 full updated

zarev@belginux:/srv/appdata/ownshare$ sudo python3 build.py
[sudo] Mot de passe de zarev : 
starting build...
building sveltekit app...
Build failed with error: failed to load config from /srv/appdata/ownshare/frontend/vite.config.js
error during build:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@sveltejs/kit' imported from /srv/appdata/ownshare/frontend/vite.config.js.timestamp-1718011854305-adb3172682994.mjs
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:916:9)
    at moduleResolve (node:internal/modules/esm/resolve:973:20)
    at defaultResolve (node:internal/modules/esm/resolve:1193:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:403:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:372:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:249:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)
    at link (node:internal/modules/esm/module_job:75:36)

zarev@belginux:/srv/appdata/ownshare$ 

Thank's in advance :)

**Comment by Das-Felix** [comment]
Hi, before building you have to install all the npm dependencies.
`cd frontend`
`npm install` 

After that the build script should work!
If there are any other problems, just let me know!

**Comment by zarevskaya** [comment]
Thank you very much!
Ok, that work now I can launch the docker-compose.

I have a blank page and nothing convincing in the logs.

I continue to look for why. :)

**Comment by Das-Felix** [comment]
Before using the ap pyou have to go to the /api/installer.php file in your browser to create all the database tables and the admin user.

**Comment by zarevskaya** [comment]
It was a blank page. But I try again.

Cheers!

**Comment by zarevskaya** [comment]
I am not more successful.

created admin user

Warning: file_put_contents(/var/www/html/api/config.php): Failed to open stream: Permission denied in /var/www/html/api/installer.php on line 56
updated config set APP_SETUP_COMPLETE to true, this endpoint is now unavailable!
You can now login to the dashboard with username: admin, password: admin.
It is recommended to then create a new admin user and delete the default one for security reasons!
