### ISSUE TITLE
How to set docker-compose?

### ISSUE THREAD

**Issue by zarevskaya** [Das-Felix/ownshare#6]
Hi, again :)

How to set the docker-compose?

I need two URL? One for the root: https://ownshare.mydomain.com & one for the api? https://ownshare.mydomain.com/api?

ROOT_URL: /
BACKEND_ADDRESS: /api

When I'm going to /api/installer.php:

created admin user

Warning: file_put_contents(/var/www/html/api/config.php): Failed to open stream: Permission denied in /var/www/html/api/installer.php on line 56
updated config set APP_SETUP_COMPLETE to true, this endpoint is now unavailable!
You can now login to the dashboard with username: admin, password: admin.
It is recommended to then create a new admin user and delete the default one for security reasons!

Thanks again!

**Comment by Das-Felix** [comment]
Hello, you only need one domain, the api is just a subdirectory of that. If you are running the app on the root of a domain or subdomain, then you can set ROOT_URL to "/" and BACKEND_ADDRESS to "/api". If you are running it on a subfolder like ww.yourdomain.com/ownshare then you have to set them to absolute URLs.

If you got that output on the installer, you should be able to login to the admin dashboard. It is located at /admin.

**Comment by zarevskaya** [comment]
Hi,

Ok, I start a new gresh install to try.
Thank you very much!

**Comment by zarevskaya** [comment]
I am not more successful.

created admin user

Warning: file_put_contents(/var/www/html/api/config.php): Failed to open stream: Permission denied in /var/www/html/api/installer.php on line 56
updated config set APP_SETUP_COMPLETE to true, this endpoint is now unavailable!
You can now login to the dashboard with username: admin, password: admin.
It is recommended to then create a new admin user and delete the default one for security reasons!

**Comment by Das-Felix** [comment]
If You go to /admin can you login with username: admin and password: admin?

**Comment by zarevskaya** [comment]
Oh, yes! 
![Screenshot_20240610_202856](https://github.com/Das-Felix/ownshare/assets/60230221/75dd5724-e6c8-4bb4-87f7-ebf83172b05c)

If I understand correctly I should not go to the root of the URL? 

Only on https://mydomain.com/admin?

**Comment by Das-Felix** [comment]
Yes, the root of the url is there to serve the single Collection views. If you want to manage files or settings you have to use the admin dashboard. 

The problem with the progressbar is an issue with PHP outputting warnings, i will look into fixing it.
Thanks for the feedback i will reply when the issue is fixed!

**Comment by zarevskaya** [comment]
Hey, cool, ok. 
On the root url I have this issue:

![Screenshot_20240610_211922](https://github.com/Das-Felix/ownshare/assets/60230221/1cf7b053-3937-4753-bbcc-39ff08279669)

When I'm trying to download a file I have an other issue:
![Screenshot_20240610_211922](https://github.com/Das-Felix/ownshare/assets/60230221/a6ad497a-bd7e-437a-ac0d-cbb0a70c9c5a)

Sorry to ask you so much.

**Comment by Das-Felix** [comment]
It looks like it has a permission error, i will test it myself ok ubuntu and See what the error is

**Comment by Das-Felix** [comment]
I have fixed the permission issue. Just remove the old install and reinstall from the git repo and follow the same steps you did before. 

Just let me know if there are more issues!

**Comment by zarevskaya** [comment]
Ok, I'm tryinh today, thanks Das-Felix!

**Comment by zarevskaya** [comment]
Hi :)

I have a suggestion, after the upload, is it possible for the window to close automatically? Or is there any point in keeping it open?

Progress bar => ok
**Collection** => I still have the problem displaying files
![338314689-1cf7b053-3937-4753-bbcc-39ff08279669](https://github.com/Das-Felix/ownshare/assets/60230221/1b1176cb-b54d-42c0-918f-248372a4d78e)
Downloads => Fixed!

**Comment by Das-Felix** [comment]
When you upload a file and click the link button on its entry, it shows collection not found?

**Comment by zarevskaya** [comment]
No, I can download. It's at the root of the url, not collection.

**Comment by zarevskaya** [comment]
Sorry, but can you tell me how to set a public endpoint to see all collections?

**Comment by zarevskaya** [comment]
Thank you for all your explanations and corrections, it allowed me to understand your work and make a tutorial!

https://belginux.com/installer-ownshare-avec-docker/

**Comment by Das-Felix** [comment]
The idea behind this tool is to work like WeTransfer, so you can create a File Collection that contains one or multiple files and share a link to that one collection, if you want to you can also password protect it. That is why there is no way to see all collections, only if you are logged in. If you want someone to download your files you have to send him the link to the collection.

Thanks for creating the tutorial and being interested in this project!
