### ISSUE TITLE
Large batch of files => can't see the title or description

### ISSUE THREAD

**Issue by zarevskaya** [Das-Felix/ownshare#9]
Hello,

I've noticed that if we have a large batch of files, we can't see the title or description:

![Screenshot_20240614_103129](https://github.com/Das-Felix/ownshare/assets/60230221/685ccacb-ded3-4026-98cf-5fffb9acaebc)

You have to reduce the size of the Mozilla interface scale to see the header (here 80%).
![Screenshot_20240614_103224](https://github.com/Das-Felix/ownshare/assets/60230221/3f5d9fd5-c6ee-4141-8bca-a44429b45643)

Have a nice day

**Comment by Das-Felix** [comment]
Thanks for the bug report, i fixed this issue in the newest version!
